name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t cpp_image:0.1 ./
        docker run -it --rm --name test_cpp cpp_image:0.1
        docker image rm -f cpp_image:0.1
        docker container rm -f tesst_cpp
